### ISSUE TITLE
SENSOR NÃO APARECE APÓS INSTALAÇÃO. HELPPP

### ISSUE THREAD

**Issue by fabHAgithub** [hudsonbrendon/sensor.instagram#3]
![image](https://user-images.githubusercontent.com/85220859/135653093-dcac2ae9-47a5-487c-967e-5035e58c3685.png)

![image](https://user-images.githubusercontent.com/85220859/135653190-8049391d-44b8-4a04-87c2-fbca5deae058.png)

**Comment by michaellunzer** [comment]
I'm having the same issue as well. 

https://community.home-assistant.io/t/custom-components-instagram-for-home-assistant/283672/5?u=lunz
